#!/usr/bin/env python3
import logging
import sys


if __name__ == '__main__':
    #formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    formatter = logging.Formatter('%(name)s %(levelname)s: %(message)s')
    handler = logging.StreamHandler(sys.stderr)
    handler.setFormatter(formatter)
    logger = logging.getLogger()
    logger.setLevel(logging.NOTSET)
    logger.addHandler(handler)
    logger.addHandler(logging.NullHandler())
    logger.propagate = False

    shapely_logger = logging.getLogger('shapely')
    shapely_logger.setLevel(logging.WARN)

    from roboime.main import Main
    app = Main()
    app.mainloop()
