# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discrete.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='discrete.proto',
  package='roboime',
  serialized_pb='\n\x0e\x64iscrete.proto\x12\x07roboime\"\xa6\x02\n\x06\x41\x63tion\x12\x10\n\x08robot_id\x18\x01 \x02(\x05\x12\"\n\x04type\x18\x02 \x02(\x0e\x32\x14.roboime.Action.Type\x12\"\n\x04move\x18\x03 \x01(\x0b\x32\x14.roboime.Action.Move\x12\"\n\x04pass\x18\x04 \x01(\x0b\x32\x14.roboime.Action.Pass\x12\"\n\x04kick\x18\x05 \x01(\x0b\x32\x14.roboime.Action.Kick\x1a\x1c\n\x04Move\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x1a\x18\n\x04Pass\x12\x10\n\x08robot_id\x18\x01 \x02(\x05\x1a\x1c\n\x04Kick\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\"$\n\x04Type\x12\x08\n\x04MOVE\x10\x00\x12\x08\n\x04PASS\x10\x01\x12\x08\n\x04KICK\x10\x02\"*\n\x07\x43ommand\x12\x1f\n\x06\x61\x63tion\x18\x01 \x03(\x0b\x32\x0f.roboime.Action')



_ACTION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='roboime.Action.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOVE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PASS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KICK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=286,
  serialized_end=322,
)


_ACTION_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='roboime.Action.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='roboime.Action.Move.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='roboime.Action.Move.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=200,
  serialized_end=228,
)

_ACTION_PASS = _descriptor.Descriptor(
  name='Pass',
  full_name='roboime.Action.Pass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='roboime.Action.Pass.robot_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=230,
  serialized_end=254,
)

_ACTION_KICK = _descriptor.Descriptor(
  name='Kick',
  full_name='roboime.Action.Kick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='roboime.Action.Kick.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='roboime.Action.Kick.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=256,
  serialized_end=284,
)

_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='roboime.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='roboime.Action.robot_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='roboime.Action.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='move', full_name='roboime.Action.move', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pass', full_name='roboime.Action.pass', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kick', full_name='roboime.Action.kick', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACTION_MOVE, _ACTION_PASS, _ACTION_KICK, ],
  enum_types=[
    _ACTION_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=322,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='roboime.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='roboime.Command.action', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=324,
  serialized_end=366,
)

_ACTION_MOVE.containing_type = _ACTION;
_ACTION_PASS.containing_type = _ACTION;
_ACTION_KICK.containing_type = _ACTION;
_ACTION.fields_by_name['type'].enum_type = _ACTION_TYPE
_ACTION.fields_by_name['move'].message_type = _ACTION_MOVE
_ACTION.fields_by_name['pass'].message_type = _ACTION_PASS
_ACTION.fields_by_name['kick'].message_type = _ACTION_KICK
_ACTION_TYPE.containing_type = _ACTION;
_COMMAND.fields_by_name['action'].message_type = _ACTION
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND

class Action(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Move(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ACTION_MOVE

    # @@protoc_insertion_point(class_scope:roboime.Action.Move)

  class Pass(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ACTION_PASS

    # @@protoc_insertion_point(class_scope:roboime.Action.Pass)

  class Kick(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ACTION_KICK

    # @@protoc_insertion_point(class_scope:roboime.Action.Kick)
  DESCRIPTOR = _ACTION

  # @@protoc_insertion_point(class_scope:roboime.Action)

class Command(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMAND

  # @@protoc_insertion_point(class_scope:roboime.Command)


# @@protoc_insertion_point(module_scope)
