# this is the default configuration
# usually you do NOT want to modify this file
# you can roll your own development.yaml
interface:
  debug: false
  control_active_only: true #false
  default: tx #sim
  log-file: "interface.log"
  command-yellow: true
  command-blue: true
  txver: 2014
  oldtx_addr: 127.0.0.1
  oldtx_port: 9050
  robots-onthefield: [0, 1, 2, 3, 4, 5]
  sim:
    vision-intf: 127.0.0.1
    vision-addr: 224.5.23.2
    vision-port: 11002
    referee-addr: 224.5.23.1
    referee-port: 10003
    grsim-addr: 127.0.0.1
    grsim-port: 20011
  tx:
    vision-intf: 127.0.0.1
    vision-addr: 224.5.23.2
    vision-port: 10002
    referee-addr: 224.5.23.1
    referee-port: 10003
cli:
  debug: false
  main_thread: true
zmq:
  # you should subscribe to this:
  pub: tcp://*:6665
  # and push to this:
  pull: tcp://*:6664
robot:
  max_speed: 2.0
