# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='messages_internal_command.proto',
  package='',
  serialized_pb='\n\x1fmessages_internal_command.proto\")\n\x0c\x43ommandWheel\x12\n\n\x02id\x18\x01 \x02(\r\x12\r\n\x05speed\x18\x02 \x02(\x01\"5\n\rCommandKicker\x12\r\n\x05speed\x18\x01 \x02(\x01\x12\x15\n\x06\x66orced\x18\x02 \x01(\x08:\x05\x66\x61lse\"7\n\x0f\x43ommandDribbler\x12\r\n\x05speed\x18\x01 \x02(\x01\x12\x15\n\x06\x66orced\x18\x02 \x01(\x08:\x05\x66\x61lse\"}\n\x0c\x43ommandRobot\x12\n\n\x02id\x18\x01 \x02(\r\x12\x1d\n\x06wheels\x18\x02 \x03(\x0b\x32\r.CommandWheel\x12\x1e\n\x06kicker\x18\x03 \x01(\x0b\x32\x0e.CommandKicker\x12\"\n\x08\x64ribbler\x18\x04 \x01(\x0b\x32\x10.CommandDribbler\"/\n\x0eToTransmission\x12\x1d\n\x06robots\x18\x01 \x03(\x0b\x32\r.CommandRobot')




_COMMANDWHEEL = descriptor.Descriptor(
  name='CommandWheel',
  full_name='CommandWheel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='CommandWheel.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='speed', full_name='CommandWheel.speed', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=76,
)


_COMMANDKICKER = descriptor.Descriptor(
  name='CommandKicker',
  full_name='CommandKicker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='speed', full_name='CommandKicker.speed', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='forced', full_name='CommandKicker.forced', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=131,
)


_COMMANDDRIBBLER = descriptor.Descriptor(
  name='CommandDribbler',
  full_name='CommandDribbler',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='speed', full_name='CommandDribbler.speed', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='forced', full_name='CommandDribbler.forced', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=133,
  serialized_end=188,
)


_COMMANDROBOT = descriptor.Descriptor(
  name='CommandRobot',
  full_name='CommandRobot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='CommandRobot.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wheels', full_name='CommandRobot.wheels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kicker', full_name='CommandRobot.kicker', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dribbler', full_name='CommandRobot.dribbler', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=190,
  serialized_end=315,
)


_TOTRANSMISSION = descriptor.Descriptor(
  name='ToTransmission',
  full_name='ToTransmission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='robots', full_name='ToTransmission.robots', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=317,
  serialized_end=364,
)

_COMMANDROBOT.fields_by_name['wheels'].message_type = _COMMANDWHEEL
_COMMANDROBOT.fields_by_name['kicker'].message_type = _COMMANDKICKER
_COMMANDROBOT.fields_by_name['dribbler'].message_type = _COMMANDDRIBBLER
_TOTRANSMISSION.fields_by_name['robots'].message_type = _COMMANDROBOT
DESCRIPTOR.message_types_by_name['CommandWheel'] = _COMMANDWHEEL
DESCRIPTOR.message_types_by_name['CommandKicker'] = _COMMANDKICKER
DESCRIPTOR.message_types_by_name['CommandDribbler'] = _COMMANDDRIBBLER
DESCRIPTOR.message_types_by_name['CommandRobot'] = _COMMANDROBOT
DESCRIPTOR.message_types_by_name['ToTransmission'] = _TOTRANSMISSION

class CommandWheel(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMANDWHEEL
  
  # @@protoc_insertion_point(class_scope:CommandWheel)

class CommandKicker(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMANDKICKER
  
  # @@protoc_insertion_point(class_scope:CommandKicker)

class CommandDribbler(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMANDDRIBBLER
  
  # @@protoc_insertion_point(class_scope:CommandDribbler)

class CommandRobot(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMANDROBOT
  
  # @@protoc_insertion_point(class_scope:CommandRobot)

class ToTransmission(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TOTRANSMISSION
  
  # @@protoc_insertion_point(class_scope:ToTransmission)

# @@protoc_insertion_point(module_scope)
